From ec2bfe91b7bf7424eb34ad371ec25eec62cd3d24 Mon Sep 17 00:00:00 2001
From: Brian Waldon <brian.waldon@rackspace.com>
Date: Mon, 26 Sep 2011 13:57:34 -0400
Subject: [PATCH 31/40] Explicit errors on confirm/revertResize failures

Fixing bug 856527

(cherry picked from commit 261b4111d481562760321bfc83d64ba35e981b5b)

Change-Id: I3664875a3d7f0da5603bb23ca01b990ed08eed68
---
 nova/api/openstack/servers.py                   |    6 +++++
 nova/tests/api/openstack/test_server_actions.py |   28 +++++++++++++++++++++++
 2 files changed, 34 insertions(+), 0 deletions(-)

diff --git a/nova/api/openstack/servers.py b/nova/api/openstack/servers.py
index fc14234..e32a6ff 100644
--- a/nova/api/openstack/servers.py
+++ b/nova/api/openstack/servers.py
@@ -305,6 +305,9 @@ class Controller(object):
     def _action_confirm_resize(self, input_dict, req, id):
         try:
             self.compute_api.confirm_resize(req.environ['nova.context'], id)
+        except exception.MigrationNotFound:
+            msg = _("Instance has not been resized.")
+            raise exc.HTTPBadRequest(explanation=msg)
         except Exception, e:
             LOG.exception(_("Error in confirm-resize %s"), e)
             raise exc.HTTPBadRequest()
@@ -313,6 +316,9 @@ class Controller(object):
     def _action_revert_resize(self, input_dict, req, id):
         try:
             self.compute_api.revert_resize(req.environ['nova.context'], id)
+        except exception.MigrationNotFound:
+            msg = _("Instance has not been resized.")
+            raise exc.HTTPBadRequest(explanation=msg)
         except Exception, e:
             LOG.exception(_("Error in revert-resize %s"), e)
             raise exc.HTTPBadRequest()
diff --git a/nova/tests/api/openstack/test_server_actions.py b/nova/tests/api/openstack/test_server_actions.py
index 6a0feda..eb4ec05 100644
--- a/nova/tests/api/openstack/test_server_actions.py
+++ b/nova/tests/api/openstack/test_server_actions.py
@@ -271,6 +271,20 @@ class ServerActionsTest(test.TestCase):
         res = req.get_response(fakes.wsgi_app())
         self.assertEqual(res.status_int, 400)
 
+    def test_confirm_resize_migration_not_found(self):
+        req = self.webreq('/1/action', 'POST', dict(confirmResize=None))
+
+        def confirm_resize_mock(*args):
+            raise exception.MigrationNotFoundByStatus(instance_id=1,
+                                                      status='finished')
+
+        self.stubs.Set(nova.compute.api.API,
+                       'confirm_resize',
+                       confirm_resize_mock)
+
+        res = req.get_response(fakes.wsgi_app())
+        self.assertEqual(res.status_int, 400)
+
     def test_revert_resize_server(self):
         req = self.webreq('/1/action', 'POST', dict(revertResize=None))
 
@@ -315,6 +329,20 @@ class ServerActionsTest(test.TestCase):
         self.assertEqual(res.status_int, 202)
         self.assertEqual(self.resize_called, True)
 
+    def test_revert_resize_migration_not_found(self):
+        req = self.webreq('/1/action', 'POST', dict(revertResize=None))
+
+        def revert_resize_mock(*args):
+            raise exception.MigrationNotFoundByStatus(instance_id=1,
+                                                      status='finished')
+
+        self.stubs.Set(nova.compute.api.API,
+                       'revert_resize',
+                       revert_resize_mock)
+
+        res = req.get_response(fakes.wsgi_app())
+        self.assertEqual(res.status_int, 400)
+
     def test_create_backup(self):
         """The happy path for creating backups"""
         self.flags(allow_admin_api=True)
-- 
1.7.6.4

