From c206f73d03aa487868ba2acaa3581624160d1b67 Mon Sep 17 00:00:00 2001
From: Josh Kearney <josh@jk0.org>
Date: Thu, 20 Oct 2011 14:44:11 -0500
Subject: [PATCH 32/40] Adds ext4 and reiserfs to _mount_filesystem().

Fixes bug 870495.

(cherry picked from commit 71f2b0dfac30537054376d583323f9912078788c)

Change-Id: Ie19d5ecf5764eb93346fa773f6437c2370ad7a5b
---
 nova/virt/xenapi/vm_utils.py |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/nova/virt/xenapi/vm_utils.py b/nova/virt/xenapi/vm_utils.py
index 302238c..2d82781 100644
--- a/nova/virt/xenapi/vm_utils.py
+++ b/nova/virt/xenapi/vm_utils.py
@@ -1161,7 +1161,7 @@ def _mount_filesystem(dev_path, dir):
     """mounts the device specified by dev_path in dir"""
     try:
         out, err = utils.execute('mount',
-                                 '-t', 'ext2,ext3',
+                                 '-t', 'ext2,ext3,ext4,reiserfs',
                                  dev_path, dir, run_as_root=True)
     except exception.ProcessExecutionError as e:
         err = str(e)
-- 
1.7.6.4

